### ISSUE TITLE
setUserId random failures

### ISSUE THREAD

**Issue by mea-licensing** [pusher/push-notifications-android#82]
When using the authenticated users login flow I get random failures in the `setUserId` call.

Process:
- Request session token from server
- Receive session token
- Request beams auth token from server
- Receive beams auth token
- Call setUserId with pusher SDK

At this point, the setUserId calls back to `onFailure` inconsistently.
This only happens sometimes, other times setUserId calls back to `onSuccess` and everything works fine.

Stack trace:
```2019-06-07 15:45:43.502 15435-15521 E/ServerSyncProcessHandler: Fail to make a valid request to the server for job (SetUserIdJob(userId=3)), skipping it
    com.pusher.pushnotifications.api.PushNotificationsAPIBadRequest: A request to the server has been deemed invalid
        at com.pusher.pushnotifications.api.PushNotificationsAPI$setUserId$1.invoke(PushNotificationsAPI.kt:301)
        at com.pusher.pushnotifications.api.PushNotificationsAPI$setUserId$1.invoke(PushNotificationsAPI.kt:77)
        at com.pusher.pushnotifications.api.RetryStrategy$WithInfiniteExpBackOff.retry(PushNotificationsAPI.kt:45)
        at com.pusher.pushnotifications.api.PushNotificationsAPI.setUserId(PushNotificationsAPI.kt:294)
        at com.pusher.pushnotifications.internal.ServerSyncProcessHandler.processSetUserIdJob(ServerSyncHandler.kt:391)
        at com.pusher.pushnotifications.internal.ServerSyncProcessHandler.processJob(ServerSyncHandler.kt:454)
        at com.pusher.pushnotifications.internal.ServerSyncProcessHandler.handleMessage(ServerSyncHandler.kt:495)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

How can I ensure my users id's are always set correctly?

**Comment by mea-licensing** [comment]
This is fixed in 1.6.0 with a new message

```
com.pusher.pushnotifications.api.PushNotificationsAPIUnprocessableEntity: The request was deemed to be unprocessable: Unprocessable Entity: User has reached the maximum of 10 devices
```
